### ISSUE TITLE
Ugyldige argumenter feilmelding

### ISSUE THREAD

**Issue by kennethnilssen** [VHamar/HomeyPro#2]
Jeg har vært en tilhenger av dette scriptet, og fått gode varsler, men nå feiler det ved kjøring. Har bygget en lik flow som deg, bare lagt på pushvarsel. Ved kjøring får jeg "Ugyldige argumenter."
Homey har også laget noen duplikater ser det ut til, har du noen gode tips?

![image](https://user-images.githubusercontent.com/60935848/224109723-7b9dd596-e3de-4b64-b03b-c7536d38c31b.png)

**Comment by VHamar** [comment]
Hei, ser ut til at renholds selskapet ditt muligens har byttet litt "fraksjoner", du kan fjærne "duplikater" ved å restartet homey'en

Etter restart, kjør rest-getaddressinfo.js for å få satt tag'ene for adresse, etter det kan du prøve å kjøre rest-mrendatoer.js manuelt fra HomeyScripts, om du får feilmeldinger der så kan du gi dem til meg. 

Har akkurat kjørt de selv uten problemer, så trenger litt mere info

**Comment by kennethnilssen** [comment]
Hei og takk for rask respons Vegard,

Når jeg kjører "rest-getaddressinfo.js" får jeg korrekt adresse, og
scriptet slutter med:

      stedfestingverifisert: false,
      representasjonspunkt: [Object],
      oppdateringsdato: '2021-09-29T17:56:56'
    }
  ]
}

———————————————————
✅ Script Success

↩️ Returned: undefined



Når jeg kjører "rest-mrendatoer.js" får jeg
Min adresse og:

Restavfall 15-03-2023

Papp, papir, kartong 20-03-2023

———————————————————
✅ Script Success

↩️ Returned: undefined


Når jeg forsøker å trigge flow, får jeg kun dette som feilmelding

[image: image.png]




tor. 9. mar. 2023 kl. 19:25 skrev Vegard Hamar ***@***.***>:

**Comment by kennethnilssen** [comment]
Lukker denne, løsning ble å fjerne "homey script" og legge opp på nytt

**Comment by VHamar** [comment]
> Lukker denne, løsning ble å fjerne "homey script" og legge opp på nytt

Skulle akkurat til å svare at for meg ser det ut som scriptene returnerte det de skulle. 

Ang duplicater så regner jeg med at de også er bort og at du har kun 4 tags nå 2 med Restavfall og 2 med Papp, papir, kartong

Lykke til videre med Homey :)
